version: "3"

services:
  api:
    image: "gabrielmorettii/streaming-server_api"
    mem_limit: 128m
    hostname: api
    environment:
      - AWS_REGION=$AWS_REGION
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - S3_BUCKET_NAME=gm-videos

  client:
    image: "gabrielmorettii/streaming-server_client"
    mem_limit: 128m
    hostname: client
    ports:
      - "80:80"
    depends_on:
      - api
