version: '3'

services:
  client:
    restart: always
    build:
      context: ./client
    ports:
      - "8000:80"
    depends_on:
      - api

  api:
    build:  
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app